config/routes.rb
Rails.application.routes.draw do
  get '/artists' , to: 'artists#index'

  get '/artists/:id', to: 'artists#show', as: 'artist'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  image_url   :string
#  name        :string
#  released_at :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  artist_id   :integer          not null
#
# Indexes
#
#  index_albums_on_artist_id  (artist_id)
#
# Foreign Keys
#
#  artist_id  (artist_id => artists.id)
#
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  image_url  :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer          not null, primary key
#  name        :string
#  number      :integer
#  preview_url :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  album_id    :integer
#
# Indexes
#
#  index_songs_on_album_id  (album_id)
#
# Foreign Keys
#
#  album_id  (album_id => albums.id)
#
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @albums = @artist.albums
    
    if @albums.count > 0
      render :show
    else
      redirect_to artists_path, notice: "El artista #{ @artist.name } aun no tiene albums registrados en la Base de Datos" 
    end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/artists/artist.html.erb
<div class="row">
  <div class="col-sm-8">
    <h1><%= @artist.name %></h1>
    <h2>Albums (<%= @albums.count %>)</h2>
    <div class="row">
    <% @albums.each do |album| %>
      <div class="col-sm-6 col-md-4 col-lg-3 mb-3">
        <div class="card bg-light ">
          <img src="<%= album.image_url %>" class="card-img-top img-fluid" alt="<%= album.name %>">
          <div class="card-body">
            <h5 class="card-title"><%= album.name %></h5>
            <h6><%= album.released_at %></h6>
          </div>
        </div>           
      </div>
    <% end %>
    </div>
  </div>
  <div class="col-sm-4 mt-3">
    <img src="<%= @artist.image_url %>" class="img-thumbnail">
  </div>
</div>

app/views/artists/index.html.erb
<div class="row mt-3">
  <% @artists.each do |artist| %>
  <div class="col-sm-6 col-md-4 col-lg-3 mb-3">
    <div class="card">
      <img src="<%= artist.image_url %>" class="card-img-top" alt="<%= artist.name%>">
      <div class="card-body">
        <h5 class="card-title text-center"><strong><%= artist.name %></strong></h5>
        <%= link_to "Ver más", artist_path(artist), class: 'btn btn-primary btn-block', target: '_blank' %>
      </div>
    </div>    
  </div>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="row">
  <div class="col-sm-8">
    <h1><%= @artist.name %></h1>
    <h2>Albums (<%= @albums.count %>)</h2>
    <div class="row">
    <% @albums.each do |album| %>
      <div class="col-sm-6 col-md-4 col-lg-3 mb-3">
        <div class="card bg-light ">
          <img src="<%= album.image_url %>" class="card-img-top img-fluid" alt="<%= album.name %>">
          <div class="card-body">
            <h5 class="card-title"><%= album.name %></h5>
            <h6><%= album.released_at %></h6>
          </div>
        </div>           
      </div>
    <% end %>
    </div>
  </div>
  <div class="col-sm-4 mt-3">
    <img src="<%= @artist.image_url %>" class="img-thumbnail">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      body {
        background-color: #F5F5F2;
      }
    </style>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Real Music</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= artists_path %>">Artists</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">My Music</a>
        </li>
      </ul>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mi Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
          </div>
        </li>        
      </ul>
    </div>
  </nav>    

  <div class="container">
  <%= yield %>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-info text-center"><%= flash[:notice] %></div>
  <% end %>

  </body>
</html>